### ISSUE TITLE
[Nuxt Bridge - Pinia - Tailwind] Update meta API with the new `useHead` composable

### ISSUE THREAD

**Issue by jesus4497** [thisdot/starter.dev#903]
Nuxt Bridge provides a new Nuxt 3 meta API that can be accessed with a new useHead composable.

Acceptance criteria:

- [ ] Enable this feature explicitly in your `nuxt.config`
- [ ] Add `@vueuse/head` to your package.json file for it to work properly.
- [ ] Replace the native Nuxt 2 `head()` to the new composable `useHead`

**Comment by jesus4497** [comment]
Closing because the kit has been discarded
